
categories:
  - title: 'ğŸš€ Features and Improvements'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ğŸŒˆ Documentation Updates'
    labels:
      - 'documentation'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bugfix'
  - title: 'ğŸ§° Breaking Changes'
    label: 'breaking'
tag-template: ''
name-template: ''
change-template: '* $TITLE (#$NUMBER)'
change-title-escapes: ''
exclude-labels:
  - 'skip-changelog'
template: |
  ## Whatâ€™s Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
