name: Draft Release

# Any time new commits hit the 'main' branch, add them to the next release draft
on:
  push:
    branches:
      - main

jobs:
  draft-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@6db134d15f3909ccc9eefd369f02bd1e9cffdf97 # v6.2.0
        with:
          config-name: configs/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
